<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "social_stream"
 *
 * Auto generated by Extension Builder 2016-09-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Social Stream',
	'description' => 'Crawls the data from a Social Media Page and saves it as news record',
	'category' => 'plugin',
	'author' => 'Philipp Parzer',
	'author_email' => 'https://forge.typo3.org/projects/extension-social_stream',
	'author_company' => 'SIWA Online GmbH',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'news' => '5.0.0-5.99.99',
			'scheduler' => '6.2.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);