services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Socialstream\SocialStream\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Socialstream\SocialStream\Command\GetFeedCommand:
    tags:
      - name: 'console.command'
        command: 'socialstream:getfeed'
        description: 'Crawls the feed and saves news'
